<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BibliotecaApp.Datos\BibliotecaApp.Datos.csproj" />
    <ProjectReference Include="..\BibliotecaApp.Entidades\BibliotecaApp.Entidades.csproj" />
  </ItemGroup>

</Project>
